apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-project-music-streaming-service-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-project-music-streaming-service-backend
  template:
    metadata:
      labels:
        app: it-project-music-streaming-service-backend
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              check_service() {
                name="$1"
                host="$2"
                port="$3"
                echo -n "Waiting for $name..."
                until nc -z "$host" "$port" 2>/dev/null; do
                  sleep 0.25
                done
                echo " Done"
              }

              check_service "postgres-accounts-service" "postgres-accounts-service" "$ACCOUNTS_PORT"
              check_service "postgres-music-service" "postgres-music-service" "$MUSIC_PORT"
              check_service "mongodb-user-activity-service" "mongodb-user-activity-service" "$USER_ACTIVITY_PORT"
              check_service "minio-service" "minio-service" "$MINIO_PORT"

              echo "All dependencies are up!"
      containers:
        - name: it-project-music-streaming-service-backend
          image: it-project-music-streaming-service-backend-image
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: it-project-music-streaming-service-backend
spec:
  selector:
    app: it-project-music-streaming-service-backend
  ports:
    - protocol: TCP
      port: $BACKEND_PORT
      targetPort: $BACKEND_PORT
  type: NodePort
