apiVersion: apps/v1
kind: Deployment
metadata:
  name: it-project-music-streaming-service-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: it-project-music-streaming-service-backend
  template:
    metadata:
      labels:
        app: it-project-music-streaming-service-backend
    spec:
      containers:
        - name: it-project-music-streaming-service-backend
          image: it-project-music-streaming-service-backend-image
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: it-project-music-streaming-service-backend
spec:
  selector:
    app: it-project-music-streaming-service-backend
  ports:
    - protocol: TCP
      port: $BACKEND_PORT
      targetPort: 8000
  type: NodePort
