apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-accounts-pvc
  annotations:
    tilt.dev/down-policy: keep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-accounts
  template:
    metadata:
      labels:
        app: postgres-accounts
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: $POSTGRESQL_ACCOUNTS_ROOT_USER
            - name: POSTGRES_PASSWORD
              value: $POSTGRESQL_ACCOUNTS_ROOT_PASSWORD
            - name: POSTGRES_DB
              value: $POSTGRESQL_ACCOUNTS_DB
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: storage
              mountPath: /var/lib/postgresql/data
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $POSTGRESQL_ACCOUNTS_ROOT_USER
                - -d
                - $POSTGRESQL_ACCOUNTS_DB
                - -q
            periodSeconds: 10
            timeoutSeconds: 1
          readinessProbe:
            exec:
              command:
                - psql
                - -U
                - $POSTGRESQL_ACCOUNTS_ROOT_USER
                - -d
                - $POSTGRESQL_ACCOUNTS_DB
                - -c
                - "SELECT 1"
            periodSeconds: 10
            timeoutSeconds: 1
          startupProbe:
            exec:
              command:
                - psql
                - -U
                - $POSTGRESQL_ACCOUNTS_ROOT_USER
                - -d
                - $POSTGRESQL_ACCOUNTS_DB
                - -c
                - "SELECT 1"
            failureThreshold: 30
            periodSeconds: 10
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: postgres-accounts-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-accounts-service
spec:
  selector:
    app: postgres-accounts
  ports:
    - protocol: TCP
      name: db
      port: $POSTGRESQL_ACCOUNTS_PORT
      targetPort: 5432
  type: NodePort
